### PR TITLE
JS fixes

### PR DESCRIPTION
**Pull request by CSharpRU**
At least allows to use UI :)

### CODE REVIEW

**Comment by OneLiberty** [comment]
Well i can only test and 2.4 and it doesn't work (surprise surprise), so i'll have to trust you on this one

**Comment by MrPhaze62** [comment]
Just tested the changes on tizen 4.0, the controls works as usual. while this fix is made for 3.0, which i dont have, this fix still works for versions above it.

**Comment by CptCross** [comment]
Can you merge the pull request into the docker file?

**Comment by OneLiberty** [comment]
Can't merge in the docker file, but I can merge in the repo ;)

**Comment by Flarkk** [comment]
Thanks ! Can someone make a new release so that the install process works out of the box with ~the docker file~ ghcr.io ?

Asking this because for some reason I cannot install the app.
I cloned this repo, built the docker image, ran it, and when I launched `tizen install -n MoonlightNaCl.wgt -t UE43LS003` this is what I got :
```
moonlight@edf2f56ab526:~$ tizen install -n MoonlightNaCl.wgt -t UE43LS003
Transferring the package...
Transferred the package: /home/moonlight/MoonlightNaCl.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install ChqHQExU28.MoonlightNaCl
package_path /home/owner/share/tmp/sdk_tools/tmp/MoonlightNaCl.wgt
was_install_app return WAS_TRUE
app_id[ChqHQExU28.MoonlightNaCl] install start
app_id[ChqHQExU28.MoonlightNaCl] installing[8]
app_id[ChqHQExU28.MoonlightNaCl] installing[10]
app_id[ChqHQExU28.MoonlightNaCl] installing[13]
app_id[ChqHQExU28.MoonlightNaCl] installing[16]
app_id[ChqHQExU28.MoonlightNaCl] install failed[118]
spend time for wascmd is [982]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:01.937
```

**Comment by CSharpRU** [comment]
> Thanks ! Can someone make a new release so that the install process works out of the box with ~the docker file~ ghcr.io ?
> 
> Asking this because for some reason I cannot install the app. I cloned this repo, built the docker image, ran it, and when I launched `tizen install -n MoonlightNaCl.wgt -t UE43LS003` this is what I got :
> 
> ```
> moonlight@edf2f56ab526:~$ tizen install -n MoonlightNaCl.wgt -t UE43LS003
> Transferring the package...
> Transferred the package: /home/moonlight/MoonlightNaCl.wgt -> /home/owner/share/tmp/sdk_tools/tmp
> Installing the package...
> --------------------
> Platform log view
> --------------------
> install ChqHQExU28.MoonlightNaCl
> package_path /home/owner/share/tmp/sdk_tools/tmp/MoonlightNaCl.wgt
> was_install_app return WAS_TRUE
> app_id[ChqHQExU28.MoonlightNaCl] install start
> app_id[ChqHQExU28.MoonlightNaCl] installing[8]
> app_id[ChqHQExU28.MoonlightNaCl] installing[10]
> app_id[ChqHQExU28.MoonlightNaCl] installing[13]
> app_id[ChqHQExU28.MoonlightNaCl] installing[16]
> app_id[ChqHQExU28.MoonlightNaCl] install failed[118]
> spend time for wascmd is [982]ms
> cmd_ret:0
> Failed to install Tizen application.
> Total time: 00:00:01.937
> ```

Your TV is not in developer mode, ran out of free space or your built image has problems with certificate of the binary. Check everything and try again.

**Comment by Flarkk** [comment]
Thanks @CSharpRU. It must be a certificate problem then. Any idea what would be the cause considering I'm simply building the docker image with `docker build .` in the root folder of this repo ?

**Comment by Flarkk** [comment]
Ah maybe it's related to [this](https://github.com/OneLiberty/moonlight-chrome-tizen/issues/37#issuecomment-2054922744).
Let me check

**Comment by OneLiberty** [comment]
@Flarkk Delete every docker container (docker system prune or smt like that/or in the GUI) and try getting the ghcr.io again

**Comment by Flarkk** [comment]
Thanks both. It was because the previous version of the app [wasn't correctly uninstalled](https://github.com/OneLiberty/moonlight-chrome-tizen/issues/37#issuecomment-2054922744).
I uninstalled it properly, then I could install the last version from this commit.

Now I can confirm this fix works well. The UI is fully functional and the streaming resolution is super good.
Thanks @CSharpRU @OneLiberty for the fix and for the support.

**Pull request merged**
